--- # When playbook example
- hosts: "{{ hostname }}"
  tasks:
    - name: Install apache for debian
      command: echo "df -h"
      register: output    
    - name: Install apache for redhat
      set_stats: 
        data:
          readvalue: "{{ (output.stdout|from_json).link }}"
