--- # When playbook example
- hosts: "{{ hostname }}"
  tasks:
    - name: register value 
      command: echo "{{ input1 }}"
      register: output    
    - name: convert variable value
      set_stats: 
        data:
          readvalue: "{{ output.stdout }}"
